#!/usr/bin/env sh

player_cnt=$(($(playerctl -l | wc -l)))

cmd="$1"
case "$cmd" in
    play-pause|next|previous) ;;
    *) exit 1 ;;
esac

if [ "$player_cnt" -eq 0 ]; then
    exit 0

elif [ "$player_cnt" -eq 1 ]; then
    playerctl "$cmd"

else
    walker -m playerctl
fi
