#!/bin/sh

if [ $# -eq 1 ]; then
	if [ "$1" = "--startup" ]; then
		if (wpctl get-mute @DEFAULT_AUDIO_SOURCE@ | grep -q "MUTED"); then
			if [ "$(cat /sys/class/leds/hda::micmute/brightness)" = "0" ]; then
				echo "" >/var/run/mute-led-fixd.pipe
			fi
			exit
		fi
	fi
else
	echo "Usage: $0 [--startup]"
	exit 1
fi

wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
echo "" >/var/run/mute-led-fixd.pipe
