#!/usr/bin/env python

from pathlib import Path
from random import randrange
from shlex import split
from subprocess import Popen, run
from sys import argv
from time import sleep

wallpaper_dir = Path.home() / "Pictures/wallpapers"
wallpapers = list(wallpaper_dir.rglob("*.jpg")) + list(wallpaper_dir.rglob("*.png"))
current_wallpaper = wallpaper_dir / "current_wallpaper"


def init():
    Popen(["awww-daemon"], start_new_session=True)
    sleep(0.02)
    run(split("awww restore"))
    _current_wallpaper = Path(
        run(
            ["sh", "-c", "awww query | cut -c 60-"],
            capture_output=True,
            check=True,
            text=True,
        ).stdout.strip()
    )
    current_wallpaper.unlink(missing_ok=True)
    current_wallpaper.symlink_to(_current_wallpaper)


def random_wallpaper():
    wallpaper = wallpapers[randrange(len(wallpapers))]
    current_wallpaper.unlink(missing_ok=True)
    current_wallpaper.symlink_to(wallpaper)
    run(split(f"awww img '{wallpaper}' --transition-type none"), check=True)


if __name__ == "__main__":
    if len(argv) > 1 and argv[1] == "--init":
        init()
    else:
        random_wallpaper()
