#!/bin/sh

if [ $# -eq 1 ]; then
	if [ "$1" = "--init" ]; then
		pidof swww-daemon || swww-daemon
		swww restore
		exit
	fi
fi

swww img "$(find ~/Pictures/wallpapers -name "*[png|jpg]" | shuf -n 1)" --transition-type none
