{ pkgs, ... }: {
  home.packages = with pkgs; [
    batmon
    eza
    fd
    ffmpeg
    foliate
    gemini-cli
    openjdk21
    jq
    libqalculate
    lm_sensors
    localsend
    ncdu
    lmstudio
    whisper-cpp-vulkan
    pandoc
    (texliveFull.withPackages (ps: with ps; [ fontawesome6 ]))
    libreoffice-qt6-fresh
    pipenv
    pulseaudio
    python3
    qpwgraph
    ripgrep
    ugrep
    unzip
    virtiofsd
    xxd
    yt-dlp
    zoxide
    bibata-cursors
    file-roller
    fragments
    gnome-keyring
    kdePackages.kdeconnect-kde
    kdePackages.okular
    loupe
    remmina
    inetutils
    wireshark
    nautilus
    obsidian
    pavucontrol
    xournalpp
    seahorse
    typst
    typstyle
    vlc
    ani-cli
    syncplay
  ];
}
