{
  pkgs,
  zen-browser,
  ...
}: {
  # ensure common packages are installed
  home.packages = with pkgs;
    [
      batmon
      eza
      fd
      ffmpeg
      foliate
      gemini-cli
      ghc
      openjdk21
      jq
      libqalculate
      lm_sensors
      localsend
      ncdu
      nodePackages_latest.nodejs
      normcap
      ollama
      pipenv
      pulseaudio
      python3Full
      qemu
      qpwgraph
      ripgrep
      rustup
      ugrep
      unzip
      virtiofsd
      xxd
      yt-dlp
      zig
      zoxide
      bibata-cursors
      file-roller
      fragments
      gnome-keyring
      kdePackages.kdeconnect-kde
      loupe
      nautilus
      obsidian
      pavucontrol
      seahorse
      vlc
    ]
    ++ [
      zen-browser.packages.${pkgs.system}.twilight
    ];
}
